## Bisection method

* This is an important concept: One wish to **"sandwich"** the value that one wishes to compute.

In [2]:
"Find the root of a monotone function f(x) in [a,b]"
function bisection(f::Function, a::Float64, b::Float64; tol=1e-12)
    
    fa=f(a)
    v=1.0

    if fa>0.0
        v=-1.0
    end

    if fa*f(b)>0
        println("Error: f(a) and f(b) have the same sign")
        #need to close the program if this occurs
    end

    x=(a+b)/2.0; ##The mid-point of the interval [a,b]

    while(b-a>tol) & ((a<x) &(x<b))
        if v*f(x)>0
            b=x;
        else
            a=x;
        end
        x=(a+b)/2;
    end

    return x
end 


bisection

In [3]:
# define f(x)
f(x)=x+exp(x);

# define [a,b] and tol
a=-1.0; b=0.0;
tol=0;

@time x=bisection(f,a,b)
@time x=bisection(f,a,b)
@time x=bisection(f,a,b)


@printf("x = %20.15f\n", x)
@printf("f(x) = %20.15e\n\n", f(x))


  0.020130 seconds (6.13 k allocations: 300.892 KB)
  0.000009 seconds (8 allocations: 224 bytes)
  0.000009 seconds (8 allocations: 224 bytes)
x =   -0.567143290409604
f(x) = 

2.934407374646398e-13



# Fixed point iterations

Find the root of 
$$f(x)=xe^x-1 =0$$
by fixed point iterations.

* Need to come up with $g(x)$ such that 
$$ f(x^*)=0 \iff x^* = g(x^*) $$

* Introduce the fixed point iteration for $g$: $$ x_{k+1} := g(x_k).$$

**What should $g(x)$ be?** 
So that $x_k\longrightarrow x^*$

The following examples come from Gander-Gander-Kwok.

### Ex1: divide by $e^x$

$$ x=e^{-x} \implies x_{k+1}:= e^{-x_k} $$

* This fixed point iteration has a **first order** convergence rate
    * Oberve in the following computation that: **The number of correct digits grows linearly in k**

In [6]:
println("Try a few different initial guesses and observe if the iterations will converge to the same number.\n")

x=zeros(50)
x[1]=-1.5

println("\nIterating using initial guess\n\nx[1]=", x[1], "\n")

for k=1:length(x)-1
    x[k+1]=exp(-x[k]) 
    
    println("x[",k+1,"]=", round(x[k+1], 10) , ",\t difference = ", round(abs(x[k+1]-x[k]),10))
end


x[1]=-100.5
println("\nIterating using a different initial guess.\n\nx[1]=", x[1], "\n")
for k=1:length(x)-1
    x[k+1]=exp(-x[k]) 
    
    println("x[",k+1,"]=", round(x[k+1], 50) , ",\t difference = ", round(abs(x[k+1]-x[k]),10))    
end

Try a few different initial guesses and observe if the iterations will converge to the same number.


Iterating using initial guess

x[1]=-1.5

x[2]=4.4816890703,	 difference = 5.9816890703
x[3]=0.0113142864,	 difference = 4.470374784
x[4]=0.9887494794,	 difference = 0.9774351931
x[5]=0.372041646,	 difference = 0.6167078335
x[6]=0.6893255343,	 difference = 0.3172838883
x[7]=0.501914479,	 difference = 0.1874110553
x[8]=0.6053705803,	 difference = 0.1034561013
x[9]=0.5458720997,	 difference = 0.0594984806
x[10]=0.5793363239,	 difference = 0.0334642242
x[11]=0.560270081,	 difference = 0.0190662429
x[12]=0.5710548119,	 difference = 0.0107847309
x[13]=0.5649292302,	 difference = 0.0061255817
x[14]=0.5684003709,	 difference = 0.0034711407
x[15]=0.5664307936,	 difference = 0.0019695773
x[16]=0.5675475222,	 difference = 0.0011167286
x[17]=0.5669140794,	 difference = 0.0006334428
x[18]=0.5672733008,	 difference = 0.0003592214
x[19]=0.5670695607,	 difference = 0.0002037401
x[20]=0.5671851073,	 d

### Ex2: add $x$ to the equation $xe^x-1=0$

$$ x+xe^{x}=1+x \implies x(1+e^x) = 1+x $$
Define the iterations:
$$x_{k+1}(1+e^{x_k}) = 1+x_k $$
or more conveniently: 
$$x_{k+1}:= \frac{1+x_k}{1+e^{x_k}} $$

* This fixed point iteration scheme has **second order** convergence rate: $$e_{k+1} \le C e_k^2 $$
    * **The number of correct digits doubles in each iteration** (if $e_0$ is sufficiently small
    *  Oberve non-convergence resulting from using a bad initial condition: **initial error is very important**

In [4]:
x=zeros(10)

x[1]=1.567 #Initial condition that leads to very fast convergence

println("\nIterating using initial guess\n\nx[1]=", x[1], "\n")


for k=1:length(x)-1
    x[k+1]= (1.0+x[k])/(1.0+exp(x[k]))
    println("x[",k+1,"]=", round(x[k+1], 10) , ",\t difference = ", round(abs(x[k+1]-x[k]),10))    

end


x[1]=-100.5 #initial conditionthat leads to divergent iterations
println("\nIterating using initial guess\n\nx[1]=", x[1], "\n")

for k=1:length(x)-1
    x[k+1]= (1.0+x[k])/(1.0+exp(x[k]))
    println("x[",k+1,"]=", round(x[k+1], 10) , ",\t difference = ", round(abs(x[k+1]-x[k]),10))    

end


Iterating using initial guess

x[1]=1.567

x[2]=0.4431783958,	 difference = 1.1238216042
x[3]=0.564259492,	 difference = 0.1210810962
x[4]=0.5671417843,	 difference = 0.0028822922
x[5]=0.5671432904,	 difference = 1.5061e-6
x[6]=0.5671432904,	 difference = 0.0
x[7]=0.5671432904,	 difference = 0.0
x[8]=0.5671432904,	 difference = 0.0
x[9]=0.5671432904,	 difference = 0.0
x[10]=0.5671432904,	 difference = 0.0

Iterating using initial guess

x[1]=-100.5

x[2]=-99.5,	 difference = 1.0
x[3]=-98.5,	 difference = 1.0
x[4]=-97.5,	 difference = 1.0
x[5]=-96.5,	 difference = 1.0
x[6]=-95.5,	 difference = 1.0
x[7]=-94.5,	 difference = 1.0
x[8]=-93.5,	 difference = 1.0
x[9]=-92.5,	 difference = 1.0
x[10]=-91.5,	 difference = 1.0


### ex3: add $x$ to the equation $xe^x-1=0$

$$ x+xe^{x}=1+x \implies x=1+x-xe^x=:g(x)$$
Define the iterations:
$$x_{k+1} = 1+x_k - x_k e^{x_k} $$

In [7]:
x=zeros(20)
x[1]=1.5

for k=1:length(x)-1
    x[k+1]=1.0+x[k]-x[k]*exp(x[k]) 
    println("x[",k+1,"]=", round(x[k+1], 10) , ",\t difference = ", round(abs(x[k+1]-x[k]),10))    

end


x[2]=-4.2225336055,	 difference = 5.7225336055
x[3]=-3.1606251356,	 difference = 1.0619084699
x[4]=-2.0266170714,	 difference = 1.1340080643
x[5]=-0.7595483141,	 difference = 1.2670687573
x[6]=0.5958274141,	 difference = 1.3553757282
x[7]=0.5146796876,	 difference = 0.0811477264
x[8]=0.6535678153,	 difference = 0.1388881276
x[9]=0.3971573272,	 difference = 0.2564104881
x[10]=0.8063500787,	 difference = 0.4091927515
x[11]=0.000353088,	 difference = 0.8059969907
x[12]=0.9999998753,	 difference = 0.9996467873
x[13]=-0.7182812753,	 difference = 1.7182811506
x[14]=0.6319451818,	 difference = 1.350226457
x[15]=0.4430879272,	 difference = 0.1888572546
x[16]=0.7529743706,	 difference = 0.3098864434
x[17]=0.1541792715,	 difference = 0.5987950992
x[18]=0.9742983117,	 difference = 0.8201190403
x[19]=-0.6069175816,	 difference = 1.5812158933
x[20]=0.7238696687,	 difference = 1.3307872503


### A more organized way to study the iterations

* Write a general function implementing teh fixed point interation
* pass in different $g$ and $x_0$ to this function 

In [4]:
#x is a vector to store teh approximations computed along the iterations
#function assumes that x[1] is the assigned initial guess
function FixedPointItrs!(x::Array{Float64,1}, g)
    for k=1:length(x)-1
        x[k+1]=g(x[k])
    end
end

FixedPointItrs! (generic function with 1 method)

In [5]:
x=zeros(12)
x[1]=1.5

g1(y)=exp(-y)
g2(y)=(1.0+y)/(1.0+exp(y))
g3(y)=1.0+y-y*exp(y)

println("\nCompare different fixed-point iterations (different g's) for solving the same equation.\n")

FixedPointItrs!(x, g1)

y=copy(x)
FixedPointItrs!(y, g2)

z=copy(x)
FixedPointItrs!(z, g3)

println("\nSequence generated by g=", g1)
println(round(x',6))
println("\nSequence generated by g=", g2)
println(round(y',6))
println("\nSequence generated by g=", g3)
println(round(z',6))




Compare different fixed-point iterations (different g's) for solving the same equation.


Sequence generated by g=g1
[1.5 0.22313 0.800011 0.449324 0.638059 0.528317 0.589597 0.554551 0.57433 0.563082 0.569451 0.565836]

Sequence generated by g=g2
[1.5 0.456064 0.564836 0.567142 0.567143 0.567143 0.567143 0.567143 0.567143 0.567143 0.567143 0.567143]

Sequence generated by g=g3
[1.5 -4.22253 -3.16063 -2.02662 -0.759548 0.595827 0.51468 0.653568 0.397157 0.80635 0.000353 1.0]


## Two fixed point iterations to solve linear systems of equations

* Jacobi iterations
* Gauss-Seidel iterations

Let the linear system of equations be 
$$ Ax =b, $$
where $A$ is an $N\times n$ invertible matrix, and $x,b$ are two vectors in $\mathbb{R}^n$.


A general strategy in coming up with fixed point iterations is to *split* $A$ into the sum of two matrices, separate the equations accordingly by the equal sign
$$
A=M+N \implies Ax=b \iff Mx=-Nx+b
$$
and define the iterations
$$
Mx_{k+1} = -Nx_{k} +b.
$$

**Of course, $M$ has to be very simple and easy to invert.**

**Both iterative schemes can be used to solve *nonlinear* equations**


### Jacobi iterations

In the Jacobi iterations, $M$ is the diagonal of $A$ (and $N$ is $A$ with its diagonal culled out).

* Very easy parallelization


$$ 
a_{11} \mathbf{x_1^{(k+1)}} + a_{12} x_2^{(k)}+a_{13} x_3^{(k)}+...+a_{1n} x_n^{(k)}=b_1 
$$

$$ 
a_{21} x_1^{(k)} + a_{22} \mathbf{x_2^{(k+1)}}+a_{13} x_3^{(k)}+...+a_{1n} x_n^{(k)}=b_2 
$$

In [20]:
#Example: Jacobi iterations

A=[10. 2. 3.; 4. 15. 6.; 7. 8. 19.]

#What happens if the diagonal elements are smaller, but A is still invertible?
# A=[1. 2. 3.; 4. 5. 6.; 7. 8. 19.]


M=zeros(3,3)

M=diagm( diag(A),0)

N=A-M

Minv = inv(M)

b=ones(3)
x=rand(3)

#the following for-loop is only for illustrating teh concept of Jacobi iteration
#in practice, one should never allocate memory for M or Minv
for k=1:25
   x = Minv*(-N*x+b) 
   println(x)
end

println("\nChecking the residual: ", A*x-b)

[-0.201197,-0.479297,-0.205999]
[0.257659,0.202719,0.328566]
[-0.0391135,-0.133469,-0.127651]
[0.164989,0.128157,0.123239]
[0.0373968,-0.0266261,-0.0621148]
[0.12396,0.0815401,0.0500648]
[0.0686725,0.0135848,-0.0273704]
[0.105494,0.0593022,0.0216112]
[0.0816562,0.0298904,-0.011204]
[0.0973831,0.0493733,0.00996229]
[0.0871367,0.0367129,-0.00403517]
[0.093868,0.0450443,0.00507053]
[0.08947,0.039607,-0.000917375]
[0.0923538,0.043175,0.00299232]
[0.0904673,0.0408421,0.000427562]
[0.0917033,0.042371,0.00210486]
[0.0908943,0.0413705,0.00100571]
[0.0914242,0.0420259,0.00172503]
[0.0910773,0.0415969,0.00125387]
[0.0913045,0.0418778,0.00156231]
[0.0911557,0.0416939,0.00136032]
[0.0912531,0.0418143,0.00149256]
[0.0911894,0.0417355,0.00140597]
[0.0912311,0.0417871,0.00146267]
[0.0912038,0.0417533,0.00142554]

Checking the residual: [-0.000179008,-0.000332115,-0.00046188]


In [21]:
#a more appropirate way to implementing the JAcobi iterations
function JacobiIterations!(x, A, b, numitrs)
   
   xnext=copy(x)
   sum=0.0
    
   for itr=1:numitrs 
   for i=1:size(A,1)
        sum=0.0
        for j in [1:i-1; i+1:3]
            sum+=A[i,j]*x[j]
        end
        xnext[i] = (b[i]-sum)/A[i,i]
   end
    
   x.=xnext
   println(itr,": ", x)
   end 
end

x=rand(3)

JacobiIterations!(x, A, b, 25)

println(x)
println(A*x-b)

1: [-0.15236,-0.274076,-0.593638]
2: [0.332907,0.344751,0.224165]
3: [-0.0361997,-0.111774,-0.215177]
4: [0.186908,0.162391,0.113031]
5: [0.0336125,-0.0283879,-0.0846042]
6: [0.131059,0.091545,0.0522008]
7: [0.0660308,0.0108373,-0.0341985]
8: [0.108092,0.0627379,0.0237414]
9: [0.08033,0.0283456,-0.0136078]
10: [0.0984132,0.0506884,0.0111013]
11: [0.0865319,0.0359826,-0.00496842]
12: [0.094294,0.0455789,0.00560083]
13: [0.089204,0.0392813,-0.00129942]
14: [0.0925336,0.0433987,0.00322747]
15: [0.090352,0.0407001,0.000267124]
16: [0.0917799,0.0424659,0.00220713]
17: [0.0908447,0.0413092,0.000937551]
18: [0.0914569,0.0420664,0.00176915]
19: [0.091056,0.0415705,0.00122476]
20: [0.0913185,0.0418952,0.00158127]
21: [0.0911466,0.0416826,0.00134786]
22: [0.0912591,0.0418218,0.0015007]
23: [0.0911854,0.0417306,0.00140063]
24: [0.0912337,0.0417903,0.00146616]
25: [0.0912021,0.0417512,0.00142325]
[0.0912021,0.0417512,0.00142325]
[-0.000206874,-0.000383813,-0.00053379]


### Gauss-Seidel iterations

In the Gauss-Seidel iterations, $M$ is the lower triangular part of $A$ (including the diagonal)

* This algorithm is of sequential nature

$$ 
a_{11} \mathbf{x_1^{(k+1)}} + a_{12} x_2^{(k)}+a_{13} x_3^{(k)}+...+a_{1n} x_n^{(k)}=b_1 
$$

$$ 
a_{21} \mathbf{x_1^{(k+1)}} + a_{22} \mathbf{x_2^{(k+1)}}+a_{13} x_3^{(k)}+...+a_{1n} x_n^{(k)}=b_2 
$$

Solving nonlinear equations: $ f_1(x) = 0,f_2(x)=0,...,f_n(x)=0, x=(x_1,x_2,...,x_n) $

$$ f_1(\mathbf{x_1^{(k+1)}}, x_2^{(k)}, ..., x_n^{(k)})=0 $$

In [15]:
function GaussSeidelIterations!(x, A, b, numitrs)
   
   sum=0.0

   for itr=1:numitrs 
   for i=1:size(A,1)
        sum=0.0
        for j in [1:i-1; i+1:3]
            sum+=A[i,j]*x[j]
        end
        x[i] = (b[i]-sum)/A[i,i]
   end
   println(itr, ": ", x)
   end 
end

GaussSeidelIterations! (generic function with 1 method)

In [22]:
x=rand(3)

GaussSeidelIterations!(x, A, b, 25)

println(x)
println(A*x-b)

1: [-0.178479,-0.079938,0.152045]
2: [0.0703741,-0.0129178,0.0321434]
3: [0.0929406,0.0290252,0.0061692]
4: [0.0923442,0.0395739,0.00194735]
5: [0.091501,0.0414875,0.00145227]
6: [0.0912668,0.0417479,0.00142888]
7: [0.0912217,0.0417693,0.00143649]
8: [0.0912152,0.041768,0.00143945]
9: [0.0912146,0.041767,0.00144011]
10: [0.0912146,0.0417667,0.00144022]
11: [0.0912146,0.0417667,0.00144023]
12: [0.0912146,0.0417667,0.00144023]
13: [0.0912146,0.0417667,0.00144023]
14: [0.0912146,0.0417667,0.00144023]
15: [0.0912146,0.0417667,0.00144023]
16: [0.0912146,0.0417667,0.00144023]
17: [0.0912146,0.0417667,0.00144023]
18: [0.0912146,0.0417667,0.00144023]
19: [0.0912146,0.0417667,0.00144023]
20: [0.0912146,0.0417667,0.00144023]
21: [0.0912146,0.0417667,0.00144023]
22: [0.0912146,0.0417667,0.00144023]
23: [0.0912146,0.0417667,0.00144023]
24: [0.0912146,0.0417667,0.00144023]
25: [0.0912146,0.0417667,0.00144023]
[0.0912146,0.0417667,0.00144023]
[-1.11022e-16,0.0,0.0]


# Convergence of iterative algorithms

* linearly convergent algorithms: (**the error in the next step is a linear function of the current error**)
$$ e_{n+1} = a e_n $$
    
    * number of correct digits is a linear function of the number of iterations: $$ \textrm{num of accurate digits} = \alpha_0 n $$


* quadratically convergent algorithms: (**the error in the next step is a quadratic function of the current error**)
$$ e_{n+1} = a e_n^2 $$

    * number of correct digits doubles after each iterations: $$ \textrm{num of accurate digits} = \alpha_1 2^n$$


* p-th order convergent algorithms:
$$ e_{n+1} = a e_n^p $$

### Possible confusion with ***order of accuracy***

(For linearly convergent algorithms)
$$e_n \le Const\cdot \frac{1}{n^p}$$

**p-th order accurate algorithm**.

## Multi-step iterations

Use more than one previously computed approximations to predict the solution of $f(x)=0$.

E.g.
$$ x_{k+1} := g(x_k, x_{k-1}) $$

* IDEA: Use interpolation of $f$

### The secant method: $x_{k-1}, x_k \longrightarrow x_{k+1}$


$$ x_{k+1} := x_k -f(x_k)\frac{x_k-x_{k-1}}{f(x_k)-f(x_{k-1})}$$

# Iterative methods for solving nonlinear systems of equations

* Direct generalization of the fixed-point iterations for a single equation
$$ x_{k+1}:=g(x_k) $$ with $x_k$ being a vector and $g(x_k)$ also.

In [5]:
#x is an array used to store the approximations computed along the iterations
#solution at the k-th iteration is x[:,k]
#function assumes that x[:,1] is the assigned initial guess
function FixedPointItrs!(x::Array{Float64,2}, g)
    for k=1:size(x,2)-1
        x[:,k+1]=g(x[:,k])
    end
end


FixedPointItrs! (generic function with 1 method)

## Newton's method for systems
$f:\mathbb{R}^d \mapsto \mathbb{R}^d$; i.e. $f$ maps a vector of $d$ component, x, to a vector of $d$ component, denoted by $f(x_k)$. 

$f(x_*)=0$. Taylor expansion gives
$$f(x_*) = 0=f(x_k)+f^\prime(x_k)(x_*-x_k)+\ldots$$

Replace $x_*$ by $x_{k+1}$ yields Newton's method:
$$ f^\prime(x_k)(x_{k+1}-x_k))=-f(x_k), $$
where  the derivative $f^\prime(x)$ is a $d\times d$ matrix.

Here, the $g$ function that defines the fixedpoint iterations is: 
$$ g(x) := x-f^\prime(x)^{-1} f(x) $$

# Worked example: Problem 5.22 in Gander-Gander-Kwok

* radius of pipe: $r=4$

* rope length: $L=30$

Find the distance of the pipe to the ceiling above: $h$.

## Setting up equations: 

* Need to variables to describe the system. $h$ and $\theta$

* radius of pipe = r  = $(h+r)\cos\theta$

* length of rope = L = (length of rope wrapping around the pipe) + (legth of rope in the air) $$L = 2\left( r(\pi - \theta) + (h+r)\sin\theta \right)$$

* Obtain two equations: 
$$f(h,\theta):=\left(\begin{array}{c}
f_{1}(h,\theta)\\
f_{2}(h,\theta)
\end{array}\right)=\left(\begin{array}{c}
(h+4)\cos\theta-4\\
(h+4)\sin\theta+4(\pi-\theta)-15
\end{array}\right)=\left(\begin{array}{c}
0\\
0
\end{array}\right)
$$

* Derivative of $f$: $$f^{\prime}(h,\theta)=\left(\begin{array}{cc}
\frac{\partial f_{1}}{\partial h} & \frac{\partial f_{1}}{\partial\theta}\\
\frac{\partial f_{2}}{\partial h} & \frac{\partial f_{2}}{\partial\theta}
\end{array}\right)=\left(\begin{array}{cc}
\cos\theta & -(h+4)\sin\theta\\
\sin\theta & (h+4)\cos\theta-4
\end{array}\right)$$

In [8]:
f(h,θ)  = [ (h+4.0)*cos(θ)-4.0; (h+4.0)*sin(θ)+4.0*(π-θ)-15.0]

f′(h,θ) = [cos(θ) -(h+4.0)*sin(θ); sin(θ)  (h+4.0)*cos(θ)-4.0] 

Newton_prob522(x) = x - f′(x[1],x[2])\f(x[1],x[2]) #this is not usually how one should run Newton's method

Newton_prob522 (generic function with 1 method)

In [9]:
x0=[ 9.0; π/3.0]
x=zeros(2, 7)
x[:,1]=x0

g_prob522(x[:,1]) 
FixedPointItrs!(x,Newton_prob522)

x

2×7 Array{Float64,2}:
 9.0     3.68704  3.64382  3.64414  3.64414  3.64414  3.64414
 1.0472  1.0333   1.02021  1.0201   1.0201   1.0201   1.0201 

In [7]:
println("Verify that the equations are solved (f should be essentially 0): f = ", f(x[1, end], x[2,end]))

h, θ=x[:, end]

if norm(f(x[1, end], x[2,end]))<1e-10
    println("\nFound a solution: h=",round(h,10), ", θ=", round(θ,10))
else
    println("\nNewton method fails.")
end

Verify that the equations are solved (f should be essentially 0): f = [8.88178e-16, 0.0]

Found a solution: h=3.6441356991, θ=1.0201044471


In [1]:
using Gadfly

t=collect(0:0.025:2π)

P=plot( layer(x=[4cos(π/2+θ) 0.0 4cos(π/2-θ)], y=[4sin(π/2+θ)-(h+4.0) 0.0 4sin(π/2+θ)-(h+4.0)], Geom.line(preserve_order=true)),
layer(x=4sin(t), y=(4cos(t)-h-4.0), Geom.line(preserve_order=true) ), Coord.cartesian(aspect_ratio=8./15.))

#draw(PDF("pipe.pdf", 3inch, 3inch), P)


INFO: Precompiling module Gadfly.
ERROR: LoadError: UndefVarError: isconcrete not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /home/juser/.julia/v0.6/ColorTypes/src/ColorTypes.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile ColorTypes to /home/juser/.julia/lib/v0.6/ColorTypes.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:456
 [3] require(::Symbol) at ./loading.jl:398
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/juser/.julia/v0.6/Colors/src/Colors.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile Colors to /home/juser/.julia/lib/v0.6/Colors.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:456
 [3] require(::

LoadError: Failed to precompile Gadfly to /home/juser/.julia/lib/v0.6/Gadfly.ji.